#!/usr/bin/env groovy

//ENV Vars
def NAMESPACE_PREFIX = "4zq6uj-cvarjao-ocp201-tst" 
def TOOLS_NAMESPACE = "${NAMESPACE_PREFIX}-tools"
def DEV_NAMESPACE = "${NAMESPACE_PREFIX}-dev"
def PROD_NAMESPACE = "${NAMESPACE_PREFIX}-prod"


//Pipeline
node {
  stage ('Build Stage'){
    checkout scm
    sh "echo HELLO NEW WORLD! "
    sh "ls -lha templates"
    sh "oc process -f templates/loki.yaml -p  NAME=cvarjao-loki | oc apply -f - -n ${DEV_NAMESPACE} --dry-run=true --validate=true"
    sh "oc process -f templates/loki.yaml -p  NAME=cvarjao-loki | oc apply -f - -n ${DEV_NAMESPACE} --wait"
  } // end build stage
} //end node
